/**
 * Kompletní databáze svalů s jejich latinskými názvy, začátky, úpony a funkcemi
 * Používá jednoduché termíny a krátké věty pro snadné učení
 */

import { Muscle } from './muscle-parser';

export const musclesData: Muscle[] = [
  // ========== SVALY KRKU ==========
  {
    id: 'muscle-1',
    name: 'Zdvihač hlavy',
    latinName: 'Musculus sternocleidomastoideus',
    group: 'Svaly Krku',
    origin: 'Oblá šlacha na rukojeti kosti hrudní a širší plochá šlacha od vnitřní části klíční kosti.',
    insertion: 'Bradavkový výběžek.',
    function: 'Uklání hlavu na svou stranu a otáčí ji na stranu opačnou. Při oboustranné akci zadní snopce zdvihají hlavu a účastní se záklonu, přední snopce sklání hlavu a celý sval sune hlavu horizontálně dopředu.',
  },
  {
    id: 'muscle-2',
    name: 'Svaly Kloněné',
    latinName: 'Musculi scaleni',
    group: 'Svaly Krku',
    origin: 'Přední: příčné výběžky 3.-6. krčního obratle. Střední: příčné výběžky 2.-7. krčního obratle. Zadní: příčné výběžky 5.-7. krčního obratle.',
    insertion: 'Přední a střední: na první žebro. Zadní: na druhé žebro.',
    function: 'Hlavní nádechové svaly. Při oboustranné akci předklání krční páteř. Při jednostranné akci ji uklání a otáčí.',
  },
  {
    id: 'muscle-3',
    name: 'Hluboké svaly krku',
    latinName: 'Musculi profundi colli',
    group: 'Svaly Krku',
    origin: 'Přední plochy krčních a hrudních obratlů',
    insertion: 'Přední plochy krčních obratlů a týlní kost',
    function: 'Balanční pohyby hlavy. Ohraničují rizikový prostor pod týlní kostí, kde prochází tepna.',
  },

  // ========== SVALY ZAD ==========
  {
    id: 'muscle-4',
    name: 'Sval trapézový',
    latinName: 'Musculus trapezius',
    group: 'Svaly Zad',
    origin: 'Kost týlní, trny všech krčních a všech hrudních obratlů.',
    insertion: 'Horní snopce na nadpažkovou část klíční kosti, prostřední na nadpažek a přilehlou část hřebene lopatky a dolní snopce na vnitřní část hřebene lopatky.',
    function: 'Horní snopce zdvihají lopatky, prostřední snopce stahují lopatky k sobě, dolní snopce táhnou lopatku dolů.',
  },
  {
    id: 'muscle-5',
    name: 'Široký zádový sval',
    latinName: 'Musculus latissimus dorsi',
    group: 'Svaly Zad',
    origin: 'Plochá aponeuróza od trnů dolních šesti hrudních obratlů, všech bederních a křížových obratlů, od zadní části hřebene kosti kyčelní a od posledních tří až čtyř žeber.',
    insertion: 'Plochou šlachou na hřeben malého hrbolku kosti pažní.',
    function: 'Připažuje, zapažuje a rotuje paži dovnitř. Při fixaci horních končetin zdvihá trup.',
  },
  {
    id: 'muscle-6',
    name: 'Zdvihač Lopatky',
    latinName: 'Musculus levator scapulae',
    group: 'Svaly Zad',
    origin: 'Na příčných výběžcích prvních čtyř obratlů krčních.',
    insertion: 'Na horní úhel lopatky.',
    function: 'Zdvihá lopatku (za současné rotace jamkou kloubní dolů). Při fixaci lopatky provádí úklon krční páteře.',
  },
  {
    id: 'muscle-7',
    name: 'Sval Rombický',
    latinName: 'Musculi rhomboidei (major et minor)',
    group: 'Svaly Zad',
    origin: 'Na trnových výběžcích posledních dvou krčních a prvních čtyř obratlů hrudních.',
    insertion: 'Na vnitřní hraně lopatky.',
    function: 'Přitahuje lopatku k páteři a lehce ji zvedá.',
  },
  {
    id: 'muscle-8',
    name: 'Pilovitý sval zadní horní',
    latinName: 'Musculus serratus posterior superior',
    group: 'Svaly Zad',
    origin: 'Od trnů posledních dvou krčních a prvních dvou hrudních obratlů.',
    insertion: 'Na druhé až páté žebro.',
    function: 'Zdvihá žebra.',
  },
  {
    id: 'muscle-9',
    name: 'Pilovitý sval zadní dolní',
    latinName: 'Musculus serratus posterior inferior',
    group: 'Svaly Zad',
    origin: 'Od trnů posledních dvou hrudních a prvních dvou bederních obratlů.',
    insertion: 'Na čtyři dolní žebra.',
    function: 'Stahuje žebra.',
  },
  {
    id: 'muscle-10',
    name: 'Napřimovače páteře',
    latinName: 'Musculi erector spinae',
    group: 'Svaly Zad',
    origin: 'Křížová kost, hřeben kosti kyčelní, trnové a příčné výběžky obratlů',
    insertion: 'Žebra, příčné a trnové výběžky obratlů, týlní kost',
    function: 'Komplex tří skupin svalů, které přeskakují obratlové výběžky a dohromady páteř napřimují, zaklání a rotují.',
  },

  // ========== SVALY HORNÍ KONČETINY ==========
  {
    id: 'muscle-11',
    name: 'Sval Deltový',
    latinName: 'Musculus deltoideus',
    group: 'Svaly Horní končetiny',
    origin: 'Zevní třetina klíční kosti, nadpažek a trnová hrana lopatky',
    insertion: 'Deltový hrbol kosti pažní',
    function: 'Přední část ohýbá a otáčí paží dopředu. Střední část zvedá paži do strany. Zadní část natahuje a otáčí paží dozadu.',
  },
  {
    id: 'muscle-12',
    name: 'Sval Hákový',
    latinName: 'Musculus coracobrachialis',
    group: 'Svaly Horní končetiny',
    origin: 'Hákovitý výběžek lopatky',
    insertion: 'Střední část vnitřní plochy kosti pažní',
    function: 'Ohýbá paži v ramenním kloubu a přitahuje ji k tělu. Pomáhá při předpažení.',
  },
  {
    id: 'muscle-13',
    name: 'Velký sval oblý',
    latinName: 'Musculus teres major',
    group: 'Svaly Horní končetiny',
    origin: 'Dolní úhel lopatky',
    insertion: 'Hřeben malého hrbolku kosti pažní',
    function: 'Přitahuje paži k tělu a otáčí ji dovnitř. Spolupracuje se širokým zádovým svalem.',
  },

  // ========== SVALY ROTÁTOROVÉ MANŽETY ==========
  {
    id: 'muscle-14',
    name: 'Sval podlopatkový',
    latinName: 'Musculus subscapularis',
    group: 'Svaly rotátorové manžety',
    origin: 'Na přední ploše lopatky.',
    insertion: 'Na malý hrbolek kosti pažní.',
    function: 'Zajišťuje vnitřní rotaci paže. Pomáhá přitáhnout upaženou ruku k tělu.',
  },
  {
    id: 'muscle-15',
    name: 'Sval nadhřebenový',
    latinName: 'Musculus supraspinatus',
    group: 'Svaly rotátorové manžety',
    origin: 'Na lopatce z jámy nadhřebenové.',
    insertion: 'Na horní plošku velkého hrbolku kosti pažní.',
    function: 'Odpovídá za abdukci paže. Zvedá ruku do úrovně ramen (do 90 stupňů).',
  },
  {
    id: 'muscle-16',
    name: 'Sval podhřebenový',
    latinName: 'Musculus infraspinatus',
    group: 'Svaly rotátorové manžety',
    origin: 'Z jámy podhřebenové.',
    insertion: 'Na střední ploše velkého hrbolku kosti pažní.',
    function: 'Provádí vnější rotaci paže. Otáčí paži směrem ven.',
  },
  {
    id: 'muscle-17',
    name: 'Malý sval oblý',
    latinName: 'Musculus teres minor',
    group: 'Svaly rotátorové manžety',
    origin: 'Od horních dvou třetin axilárního okraje lopatky.',
    insertion: 'Dolní ploška velkého hrbolku kosti pažní.',
    function: 'Vnější rotace paže.',
  },

  // ========== EXTENZORY A FLEXY LOKETNÍHO KLOUBU ==========
  {
    id: 'muscle-18',
    name: 'Dvojhlavý sval pažní',
    latinName: 'Musculus biceps brachii',
    group: 'Extenzory a flexory loketního kloubu',
    origin: 'DLOUHÁ HLAVA: v dutině kloubu ramenního na drsnatině nad kloubní jamkou. KRÁTKÁ HLAVA: na hákovitém výběžku.',
    insertion: 'OBĚ HLAVY: na vřetenní kosti.',
    function: 'Flexe a supinaci v loketním kloubu a abdukce v kloubu ramenním.',
  },

  // ========== EXTENZORY LOKETNÍHO KLOUBU ==========
  {
    id: 'muscle-19',
    name: 'Hluboký sval pažní',
    latinName: 'Musculus brachialis',
    group: 'Extenzory loketního kloubu',
    origin: 'Přední plocha kosti pažní',
    insertion: 'Kost loketní',
    function: 'Flexe v loketním kloubu',
  },
  {
    id: 'muscle-20',
    name: 'Trojhlavý sval pažní',
    latinName: 'Musculus triceps brachii',
    group: 'Extenzory loketního kloubu',
    origin: 'DLOUHÁ HLAVA: na lopatce pod jamkou kloubu ramenního. ZEVNÍ HLAVA: odstupuje od zadní plochy kosti pažní nad žlábkem nervu vřetenního. VNITŘNÍ HLAVA: na zadní ploše kosti pažní pod žlábkem nervu vřetenního',
    insertion: 'VŠECHNY TŘI HLAVY: se spojují v silnou plochou šlachu, která se upíná na loketní výběžek kosti loketní',
    function: 'Extenze v loketním kloubu, dlouhá hlava addukce a extenze v ramenním kloubu',
  },
  {
    id: 'muscle-21',
    name: 'Sval Loketní',
    latinName: 'Musculus anconeus',
    group: 'Extenzory a flexory loketního kloubu',
    origin: 'Na vnějším epikondylu kosti pažní. (Přechází přes loket)',
    insertion: 'Na vnější okraj okovce (loktu) a přilehlou zadní stranu kosti loketní.',
    function: 'Extenze v loketním kloubu. (sinergista tricepsu)',
  },
  {
    id: 'muscle-22',
    name: 'Sval Vřetenní',
    latinName: 'Musculus brachioradialis',
    group: 'Extenzory a flexory loketního kloubu',
    origin: 'Dolní třetina zevní strany kosti pažní.',
    insertion: 'Přes silnou provazcovitou šlachu na bodcovitý výběžek kosti vřetenní.',
    function: 'Flexe v loketním kloubu.',
  },

  // ========== SVALY V OBLASTI HRUDNÍKU ==========
  {
    id: 'muscle-23',
    name: 'Velký prsní sval',
    latinName: 'Musculus pectoralis major',
    group: 'Svaly v oblasti hrudníku',
    origin: 'Od vnitřní třetiny klíční kosti, od kosti hrudní a přilehlých chrupavek pravých žeber a od pochvy přímého svalu břišního.',
    insertion: 'Na hranu velkého hrbolku kosti pažní.',
    function: 'Addukce a vnitřní rotace paže. Zatáhnu ruku k tělu, protočení je tam proto, aby se zapojovaly všechny vlákna při pohybu.',
  },
  {
    id: 'muscle-24',
    name: 'Malý prsní sval',
    latinName: 'Musculus pectoralis minor',
    group: 'Svaly v oblasti hrudníku',
    origin: 'Od předního okraje třetího až pátého žebra.',
    insertion: 'Na hákovitý výběžek.',
    function: 'Deprese a protrakce ramene. Při fixované lopatce zdvihá žebra.',
  },
  {
    id: 'muscle-25',
    name: 'Přední pilovitý sval',
    latinName: 'Musculus serratus anterior',
    group: 'Svaly v oblasti hrudníku',
    origin: 'Devět zubů od přední kostěné části horních 9 žeber (Horní: 1. a 2. žebro, Střední: 2. až 4. žebro, Dolní: 5. až 9. žebro).',
    insertion: 'Na páteřní okraj lopatky (Horní: horní úhel lopatky, Střední: po celé délce páteřního okraje, Dolní: dolní úhel lopatky).',
    function: 'Horní a střední část působí protrakci ramene. Dolní část otáčí dolní úhel lopatky vzhůru a tím umožňuje vzpažení. V klidovém napětí sval přitlačuje lopatku k hrudníku.',
  },
  {
    id: 'muscle-26',
    name: 'Sval podklíčkový',
    latinName: 'Musculus subclavius',
    group: 'Svaly v oblasti hrudníku',
    origin: 'Na hranici kostěné a chrupavčité části prvního žebra.',
    insertion: 'Na dolní plochu klíční kosti (v její střední části).',
    function: 'Deprese ramene, přitlačení sternálního konce klíční kosti do kloubní jamky na kosti hrudní.',
  },
  {
    id: 'muscle-27',
    name: 'Mezižeberní svaly',
    latinName: 'Musculi intercostales externi/ interni',
    group: 'Svaly v oblasti hrudníku',
    origin: 'ZEVNÍ: dolní okraj horního žebra. VNITŘNÍ: horní okraj dolního žebra.',
    insertion: 'ZEVNÍ: horní okraj dolního žebra. VNITŘNÍ: dolní okraj horního žebra.',
    function: 'ZEVNÍ: zdvíhají žebra (pomocné nádechové svaly). VNITŘNÍ: stahují žebra (pomocné výdechové svaly).',
  },
  {
    id: 'muscle-28',
    name: 'Bránice',
    latinName: 'Diaphragma',
    group: 'Svaly v oblasti hrudníku',
    origin: 'Od bederní páteře, vnitřní plochy 7 až 12 žebra a zadní plochy mečíkovitého výběžku.',
    insertion: 'Šlašitý střed.',
    function: 'Hlavní dýchací sval. Odděluje dutinu hrudní od dutiny břišní.',
  },

  // ========== SVALY V OBLASTI BŘICHA ==========
  {
    id: 'muscle-29',
    name: 'Šikmý sval břišní vnitřní',
    latinName: 'Musculus obliquus internus abdominis',
    group: 'Svaly v oblasti břicha',
    origin: 'Od bederní páteře, od hřebene kyčelní kosti a od zevní třetiny až poloviny tříselného vazu.',
    insertion: 'Na předním úseku tří dolních žeber a do linea alba.',
    function: 'Při oboustranné akci předklání trup. Při jednostranné akci uklání trup a otáčí ho na svou stranu. Pomáhá při břišním lisu a trávení.',
  },
  {
    id: 'muscle-30',
    name: 'Šikmý sval břišní vnější',
    latinName: 'Musculus obliquus externus abdominis',
    group: 'Svaly v oblasti břicha',
    origin: 'Osm zubů na pátém až dvanáctém žebru. Směr vláken je šikmo dolů.',
    insertion: 'Na hraně kosti kyčelní a do linea alba.',
    function: 'Při oboustranné akci předklání trup. Při jednostranné akci uklání trup a otáčí ho na opačnou stranu. Pomáhá při břišním lisu a trávení.',
  },
  {
    id: 'muscle-31',
    name: 'Přímý sval břišní',
    latinName: 'Musculus rectus abdominis',
    group: 'Svaly v oblasti břicha',
    origin: 'Od mečíkovitého výběžku kosti hrudní a od páté až sedmé žeberní chrupavky.',
    insertion: 'Kost stydká a ve střední části bílá čára (linea alba).',
    function: 'Ohýbá páteř, spolupůsobí při lisu břišním a je pomocný výdechový sval.',
  },
  {
    id: 'muscle-32',
    name: 'Příčný břišní sval',
    latinName: 'Musculus transversus abdominis',
    group: 'Svaly v oblasti břicha',
    origin: 'Od vnitřní strany chrupavek dolních šesti žeber, od bederní páteře, od hřebene kosti kyčelní a od zevní třetiny až poloviny tříselného vazu.',
    insertion: 'Do středu do linea alba.',
    function: 'Spolupůsobí při lisu břišním.',
  },
  {
    id: 'muscle-33',
    name: 'Čtyřhranný sval bederní',
    latinName: 'Musculus quadratus lumborum',
    group: 'Svaly v oblasti břicha',
    origin: 'Hrana kyčelní kosti a příčné výběžky bederních obratlů.',
    insertion: 'Dvanácté žebro.',
    function: 'Při oboustranné funkci zaklání bederní páteř a při jednostranné funkci ji uklání.',
  },

  // ========== SVALY HÝŽĎOVÉ ==========
  {
    id: 'muscle-34',
    name: 'Velký sval hýžďový',
    latinName: 'Musculus gluteus maximus',
    group: 'Svaly Hýžďové',
    origin: 'Na kosti křížové a kostrči, na vazu křížohrbolovém a od zadní části zevní plochy lopaty kosti kyčelní.',
    insertion: 'Pod velký chocholík na drsnatinu hýžďovou a horní snopce do povázky stehenní.',
    function: 'Hlavní extenzor kyčle, uplatňuje se při vnější rotaci stehna. Abdukce i addukce stehna a extenze v kloubu kolenním.',
  },
  {
    id: 'muscle-35',
    name: 'Střední sval hýžďový',
    latinName: 'Musculus gluteus medius',
    group: 'Svaly Hýžďové',
    origin: 'Na vnější ploše lopaty kosti kyčelní.',
    insertion: 'Na velký chocholík kosti stehenní.',
    function: 'Hlavní abduktor stehna (společně s malým hýžďovým svalem). Přední snopce se výrazně uplatňují při flexi a vnitřní rotaci stehna, naproti tomu zadní při extenzi a vnější rotaci.',
  },
  {
    id: 'muscle-36',
    name: 'Malý sval hýžďový',
    latinName: 'Musculus gluteus minimus',
    group: 'Svaly Hýžďové',
    origin: 'Nad jamkou kyčelního kloubu.',
    insertion: 'Na velký chocholík kosti stehenní.',
    function: 'Hlavní abduktor stehna (společně se středním hýžďovým svalem).',
  },

  // ========== FLEXY KYČELNÍHO KLOUBU ==========
  {
    id: 'muscle-37',
    name: 'Bedrokyčlostehenní sval',
    latinName: 'Musculus iliopsoas',
    group: 'Flexory kyčelního kloubu',
    origin: 'Bedrostehenní: od meziobratlových plotének a přilehlých těl horních čtyř bederních obratlů a posledního obratle hrudního. Kyčlostehenní: na vnitřní ploše lopaty kosti kyčelní.',
    insertion: 'Oba podbíhají tříselný vaz a upínají se na malý chocholík.',
    function: 'Hlavní flexor kyčle, uplatňuje se rovněž při vnější rotaci stehna.',
  },
  {
    id: 'muscle-38',
    name: 'Přímý sval stehenní',
    latinName: 'Musculus rectus femoris',
    group: 'Flexory kyčelního kloubu',
    origin: 'Dolní přední trn kyčelní kosti a nad jamkou kyčelního kloubu.',
    insertion: 'Drsnatina kosti holenní.',
    function: 'Flexe v kloubu kyčelním a extenze v kloubu kolenním.',
  },
  {
    id: 'muscle-39',
    name: 'Napínač povázky stehenní',
    latinName: 'Musculus tensor fasciae latae',
    group: 'Flexory kyčelního kloubu',
    origin: 'Na vnější části lopaty kosti kyčelní.',
    insertion: 'Do povázky stehenní, která je na vnějším obvodu stehna zesílena ve vazivový pruh kyčloholenní, přes něhož se upíná až na kost holenní.',
    function: 'Flexe, abdukce a vnitřní rotace stehna. Pomocí kyčloholenního pruhu se uplatňuje i při pohybech v kloubu kolenním a ovlivňuje v něm vnější rotaci a extenzi ve stoji.',
  },
  {
    id: 'muscle-40',
    name: 'Sval krejčovský',
    latinName: 'Musculus sartorius',
    group: 'Flexory kyčelního kloubu',
    origin: 'Horní přední trn kyčelní kosti.',
    insertion: 'Vnitřní hrbolek kosti holenní (spolu se štíhlým svalem stehenním a pološlašitým - husí nožka).',
    function: 'Flexe, abdukce a vnější rotace v kyčelním kloubu, flexe v kolenním kloubu (spolu s vnitřní rotací bérce).',
  },

  // ========== ČTYŘHLAVÝ SVAL STEHENNÍ ==========
  {
    id: 'muscle-41',
    name: 'Přímý sval stehenní',
    latinName: 'Musculus rectus femoris',
    group: 'Čtyřhlavý sval stehenní',
    origin: 'Dolní přední trn kyčelní kosti a nad jamkou kyčelního kloubu.',
    insertion: 'Drsnatina kosti holenní.',
    function: 'Flexe v kloubu kyčelním a extenze v kloubu kolenním.',
  },
  {
    id: 'muscle-42',
    name: 'Prostřední hlava čtyřhlavého svalu stehenního',
    latinName: 'Musculus vastus intermedius',
    group: 'Čtyřhlavý sval stehenní',
    origin: 'Skoro po celé přední ploše těla kosti stehenní.',
    insertion: 'Přechází ve šlachu, která se spojuje s přímým svalem stehenním.',
    function: 'Extenze v kolenním kloubu.',
  },
  {
    id: 'muscle-43',
    name: 'Vnitřní hlava čtyřhlavého svalu stehenního',
    latinName: 'Musculus vastus medialis',
    group: 'Čtyřhlavý sval stehenní',
    origin: 'Na vnitřním okraji drsné čáry kosti stehenní.',
    insertion: 'Tibiální okraj čéšky a do šlachy přímého svalu stehenního.',
    function: 'Extenze v kolenním kloubu.',
  },
  {
    id: 'muscle-44',
    name: 'Zevní hlava čtyřhlavého svalu stehenního',
    latinName: 'Musculus vastus lateralis',
    group: 'Čtyřhlavý sval stehenní',
    origin: 'Na zevním okraji drsné čáry kosti stehenní.',
    insertion: 'Do šlachy přímého svalu stehenního a na horní okraj čéšky.',
    function: 'Extenze v kolenním kloubu.',
  },

  // ========== ŠTÍHLÝ SVAL STEHENNÍ ==========
  {
    id: 'muscle-45',
    name: 'Štíhlý sval stehenní',
    latinName: 'Musculus gracilis',
    group: 'Štíhlý sval stehenní',
    origin: 'Kost stydká (těsně při sponě stydké pod začátkem dlouhého přitahovače).',
    insertion: 'Vnitřní hrbolek kosti holenní.',
    function: 'Addukce v kyčelním kloubu a flexe s vnitřní rotací v kolenním kloubu.',
  },

  // ========== SVALY ZADNÍ STRANY STEHNA ==========
  {
    id: 'muscle-46',
    name: 'Dvojhlavý sval stehenní',
    latinName: 'Musculus biceps femoris',
    group: 'Svaly zadní strany stehna',
    origin: 'DLOUHÁ HLAVA: hrbol kosti sedací. KRÁTKÁ HLAVA: zevní okraj drsné čáry kosti stehenní (v dolní polovině).',
    insertion: 'OBĚ HLAVY: na hlavici kosti lýtkové.',
    function: 'Flexe a vnější rotace v kolenním kloubu. Dlouhá hlava se uplatňuje při extenzi v kyčli.',
  },
  {
    id: 'muscle-47',
    name: 'Sval pološlašitý',
    latinName: 'Musculus semitendinosus',
    group: 'Svaly zadní strany stehna',
    origin: 'Hrbol sedací.',
    insertion: 'Vnitřní hrbolek kosti holenní (do husí nožky).',
    function: 'Flexe a vnitřní rotace v kolenním kloubu. Uplatňuje se při extenzi v kyčelním kloubu.',
  },
  {
    id: 'muscle-48',
    name: 'Sval poloblanitý',
    latinName: 'Musculus semimembranosus',
    group: 'Svaly zadní strany stehna',
    origin: 'Hrbol sedací.',
    insertion: 'Proximální konec kosti holenní třemi šlašitými pruhy, z nichž dva zůstávají na tibiálním kondylu holenní kosti, třetí se obrací vzhůru a zpevňuje zadní stěnu pouzdra kloubu kolenního (šikmý vaz zákolenní).',
    function: 'Flexe a vnitřní rotace v kolenním kloubu. Uplatňuje se při extenzi v kyčelním kloubu.',
  },

  // ========== SVALY BÉRCE ==========
  {
    id: 'muscle-49',
    name: 'Dvojhlavý sval lýtkový',
    latinName: 'Musculus gastrocnemius',
    group: 'Svaly Bérce',
    origin: 'VNITŘNÍ HLAVA: od vnitřního epikondylu kosti stehenní. ZEVNÍ HLAVA: od zevního epikondylu.',
    insertion: 'OBĚ HLAVY: přecházejí ve šlachu, upínající se na hrbol kosti patní.',
    function: 'Flexe v kloubu hlezenním a sekundárně flexe v kolenním kloubu.',
  },
  {
    id: 'muscle-50',
    name: 'Šikmý sval lýtkový',
    latinName: 'Musculus soleus',
    group: 'Svaly Bérce',
    origin: 'Od hlavice kosti lýtkové a od zadní plochy kosti holenní.',
    insertion: 'Sval přechází do šlachy Achillovy.',
    function: 'Plantární flexe (výpon) v hlezenním kloubu.',
  },
  {
    id: 'muscle-51',
    name: 'Přední sval holenní',
    latinName: 'Musculus tibialis anterior',
    group: 'Svaly Bérce',
    origin: 'Od vnějšího kondylu kosti holenní, od horních dvou třetin vnější plochy kosti holenní a přilehlé mezikostní blány.',
    insertion: 'Na vnitřní kost klínovitou a na bázi palcového metatarzu.',
    function: 'Dorzální flexe a uplatnění také při supinaci nohy.',
  },
  {
    id: 'muscle-52',
    name: 'Zadní sval holenní',
    latinName: 'Musculus tibialis posterior',
    group: 'Svaly Bérce',
    origin: 'Od zadní plochy mezikostní blány a přilehlého okraje kosti holenní i kosti lýtkové.',
    insertion: 'Na kost loďkovitou, na kosti klinovité a na báze II. a IV. Metatarzu.',
    function: 'Plantární flexe, supinace a addukce nohy.',
  },
];
